name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@master
      - name: install, lint, build and test
        run: |
          yarn install
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}

